version: "3.3"
services:
    web:
        image: "trafex/alpine-nginx-php7:1.8.0"
        ports:
            - "80:8080"
        volumes:
            - ./public:/var/www/html
            - ./src:/var/www/src
            - ./vendor:/var/www/vendor
    db-hostname:
        image: "yobasystems/alpine-mariadb:10.6"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=chat
            - MYSQL_USER=chat
            - MYSQL_PASSWORD=chat
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_CHARSET=utf8

